name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build & Test
        run: mvn -B verify

  publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }} # publish only from master
    needs: [build]
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GIT_PUSH_TOKEN }}
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -B deploy -DskipTests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Update documentation
      run: |
        mvn javadoc:javadoc
        git add docs
        git commit -am "chore(docs): update documentation"
        git push origin master
